{
    API_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJiNjQ4YTA2MDczYjE0NTU1YTUxNjU2NTJlZGM1Y2MxZSIsImlhdCI6MTY4OTExMTQ5NSwiZXhwIjoyMDA0NDcxNDk1fQ.Wze81MVws0mO7khGqKS22Hl0rWSEkTv96Ljzi0wivKc",
    URL: "homeassistant:8123",
}
